import { Component, inject } from '@angular/core';
import {
  FormGroup,
  FormBuilder,
  Validators,
  ReactiveFormsModule,
  FormControl,
} from '@angular/forms';
import { Habit } from '../../models/models';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { SupabaseService } from '../../services/supabase-service';

@Component({
  selector: 'app-habit-form',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './habit-form-page.html',
  styleUrl: './habit-form-page.css',
})
export class HabitFormPage {
  habitForm: FormGroup;
  router = inject(Router);
  supabaseService = inject(SupabaseService);
  isSubmitting: boolean = false;

  constructor() {
    this.habitForm = new FormGroup({
      title: new FormControl('', Validators.required),
      description: new FormControl(''),
      frequency: new FormControl('daily', Validators.required),
      customFrequency: new FormControl(''),
      startDate: new FormControl(''),
      endDate: new FormControl(''),
      streakEnabled: new FormControl(true),
      resetCondition: new FormControl('reset-after-1'),
      icon: new FormControl(''),
    });
  }

  async onSubmit(): Promise<void> {
    if (this.habitForm.invalid) return;

    this.isSubmitting = true;

    try {
      const newHabit: Habit = {
        id: '', // ID will be generated by the backend
        userId: '', // User ID should be set based on the logged-in user
        title: this.habitForm.value.title,
        description: this.habitForm.value.description,
        frequency: this.habitForm.value.frequency,
        startDate: this.habitForm.value.startDate
          ? new Date(this.habitForm.value.startDate + 'T00:00:00')
          : undefined,
        endDate: this.habitForm.value.endDate
          ? new Date(this.habitForm.value.endDate + 'T00:00:00')
          : undefined,
        createdAt: new Date(),
        streakEnabled: this.habitForm.value.streakEnabled,
      };
      console.log('New Habit:', newHabit);

      const { data, error } = await this.supabaseService.createHabit(newHabit);

      if (error) {
        console.error('Erreur lors de la création:', error);
        alert("Erreur lors de la création de l'habitude");
        return;
      }

      console.log('Habitude créée avec succès:', data);
      this.habitForm.reset();
      // this.router.navigate(['/all-habits']); // ou ta route de liste
    } catch (error) {
      console.error('Erreur:', error);
      alert('Une erreur est survenue');
    } finally {
      this.isSubmitting = false;
    }
  }
}
